### ISSUE TITLE
Automatically re-auth on access token expiration

### ISSUE THREAD

**Issue by z1lc** [rkhwaja/toodledo-python#7]
It would be nice if the library was able to detect when the access token has expired and automatically use the `TokenStorageFile` to refresh it.

**Comment by rkhwaja** [comment]
Isn't it doing that? I though OAuth2Session took care of that. I don't use this library anymore but I don't remember any problems with it using the refresh token to update the access token.
I do remember a problem when the refresh token expired if you haven't used it in a while. I think you need to reauthorize at that point?

**Comment by z1lc** [comment]
Yeah, it seemed like a temporary issue; it does correctly re-auth for me now on access token expiration. However, I have hit a few 429's (too many API requests) while testing, which could be an opportunity to auto trigger another refresh. Probably better as a new issue however.
